export const genres: string[] = [
  'Neo Soul',
  'Shoegaze',
  'Lo-Fi Hip Hop',
  'Post-Punk',
  'Afrobeats',
  'Dream Pop',
  'Jazz Fusion',
  'Hyperpop',
  'Indie Folk',
  'UK Garage',
  'Ambient Electronic',
  'Math Rock',
  'R&B',
  'Darkwave',
  'Bossa Nova',
  'Trap Soul',
  'Midwest Emo',
  'Nu Jazz',
  'Synthwave',
  'Gospel Blues',
  'Cumbia',
  'Footwork',
  'Ethereal Wave',
  'Outlaw Country',
  'Crunk',
  'Vaporwave',
  'Baroque Pop',
  'Grime',
  'Psychedelic Soul',
  'Noise Rock',
];

export const moods: string[] = [
  'makes you want to break shit and riot but in an empowering way',
  'feels like driving alone at 2am with nowhere to be',
  'the musical equivalent of a warm hug from someone you missed',
  'hits different when you realize you actually turned out okay',
  'makes you feel like the main character in a film nobody else has seen',
  'sounds like crying in the shower but in a healing way',
  'perfect for staring out a rain-soaked window and feeling deeply',
  'makes you want to slow dance alone in your kitchen at sunset',
  'the sonic version of letting go of something you held onto too long',
  'feels like nostalgia for a memory you never actually had',
  'the kind of song that makes a stranger feel like an old friend',
  'hits like the first warm day after a long brutal winter',
  'makes you feel invincible but in a quiet, private way',
  'sounds like falling in love with a city at golden hour',
  'the feeling of finishing something you thought you never would',
  'melancholy but make it beautiful — you feel sad in a good way',
  'makes your whole body want to move even if you swore you weren\'t dancing tonight',
  'the audio equivalent of watching the sun rise after pulling an all-nighter',
  'feels like the deep breath before something changes everything',
  'sounds like the version of yourself you\'re still becoming',
  'the sonic equivalent of texting back "lol" when you\'re actually not okay',
  'makes you want to reorganize your entire life at 11pm on a tuesday',
  'sounds like something beautiful rotting slowly and you can\'t look away',
  'the feeling of being completely alone in a crowd and somehow preferring it',
  'hits like an apology you never got but somehow still healed from',
  'makes you want to pick up a hobby you abandoned years ago for no reason',
  'sounds like two people who love each other but keep missing each other by five minutes',
  'the kind of song that makes you forgive yourself for something you\'ve been holding',
  'feels like being nineteen again but with the wisdom to actually enjoy it',
  'makes everything feel cinematic even if you\'re just doing dishes',
  'the feeling of packing a bag and not telling anyone where you\'re going',
  'sounds like a conversation you\'ve been rehearsing for months that you\'ll never actually have',
  'hits like finally admitting to yourself what you already knew',
  'makes you want to lie on the floor and stare at the ceiling until something makes sense',
  'feels like watching your old self from a distance and wishing you could warn them',
  'the kind of song you play loud enough that the neighbors can hear your feelings for you',
  'sounds like the last night in a place you\'ll never live again',
  'makes you want to call someone you haven\'t talked to in years at a completely unreasonable hour',
  'feels like being understood by someone who doesn\'t even speak your language',
  'the audio equivalent of a memory that hits you out of nowhere while you\'re in the grocery store',
  'sounds like falling apart gracefully — like you\'re okay with it this time',
  'makes you feel like the universe is conspiring in your favor for once',
  'the feeling right after a good cry when everything looks slightly cleaner',
  'sounds like someone wrote it just for you but they\'ve never met you',
  'makes you want to sit outside alone at night and just exist for a while',
  'feels like the exact moment summer turns into fall and you can\'t stop it',
];

export function getRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}
