export const genres: string[] = [
  // --- hip hop / rap ---
  'Lo-Fi Hip Hop',
  'Trap',
  'Trap Soul',
  'Boom Bap',
  'Cloud Rap',
  'Drill',
  'UK Drill',
  'Crunk',
  'Phonk',
  'Emo Rap',
  'Jazz Rap',
  'Gangsta Rap',
  'Conscious Hip Hop',
  'Chopped & Screwed',
  'Footwork',
  'Grime',
  'G-Funk',

  // --- r&b / soul ---
  'R&B',
  'Neo Soul',
  'Trap Soul',
  'Contemporary R&B',
  'Quiet Storm',
  'Gospel Blues',
  'Psychedelic Soul',
  'Motown',
  'Funk',
  'New Jack Swing',

  // --- pop ---
  'Hyperpop',
  'Synthpop',
  'Baroque Pop',
  'Chamber Pop',
  'Dream Pop',
  'Bubblegum Pop',
  'Art Pop',
  'City Pop',
  'Electropop',
  'Indie Pop',
  'K-Pop',
  'J-Pop',
  'Bedroom Pop',

  // --- rock / alternative ---
  'Shoegaze',
  'Post-Punk',
  'Math Rock',
  'Noise Rock',
  'Midwest Emo',
  'Post-Rock',
  'Grunge',
  'Indie Rock',
  'Psychedelic Rock',
  'Garage Rock',
  'Art Rock',
  'Glam Rock',
  'Stoner Rock',
  'Desert Rock',
  'Slowcore',
  'Emo',
  'Screamo',
  'Pop Punk',
  'Britpop',
  'Surf Rock',
  'Folk Rock',

  // --- metal ---
  'Doom Metal',
  'Black Metal',
  'Death Metal',
  'Sludge Metal',
  'Shoegaze Metal',
  'Post-Metal',
  'Nu-Metal',
  'Metalcore',
  'Progressive Metal',
  'Gothic Metal',

  // --- electronic ---
  'Ambient Electronic',
  'Synthwave',
  'Darkwave',
  'Ethereal Wave',
  'Vaporwave',
  'UK Garage',
  'House',
  'Deep House',
  'Tech House',
  'Acid House',
  'Chicago House',
  'Techno',
  'Detroit Techno',
  'Minimal Techno',
  'Trance',
  'Psytrance',
  'Drum and Bass',
  'Jungle',
  'Dubstep',
  'Future Bass',
  'IDM',
  'Glitch',
  'Chillwave',
  'Witch House',
  'Jersey Club',
  'Ambient',
  'New Age',
  'Trip Hop',

  // --- jazz ---
  'Jazz Fusion',
  'Nu Jazz',
  'Bebop',
  'Cool Jazz',
  'Hard Bop',
  'Free Jazz',
  'Smooth Jazz',
  'Acid Jazz',
  'Avant-Garde Jazz',
  'Modal Jazz',

  // --- folk / country / americana ---
  'Indie Folk',
  'Outlaw Country',
  'Americana',
  'Bluegrass',
  'Folk',
  'Anti-Folk',
  'Country Blues',
  'Alt-Country',
  'Appalachian Folk',
  'Singer-Songwriter',

  // --- latin / global ---
  'Afrobeats',
  'Bossa Nova',
  'Cumbia',
  'Reggaeton',
  'Latin Trap',
  'Salsa',
  'Samba',
  'Merengue',
  'Afro-Cuban Jazz',
  'Dembow',
  'Baile Funk',
  'Amapiano',
  'Afrohouse',
  'Dancehall',
  'Reggae',
  'Dub',
  'Soca',
  'Highlife',
  'Fela Kuti-era Afrobeat',
  'Flamenco',
  'Fado',

  // --- classical / orchestral ---
  'Neoclassical',
  'Minimalist Classical',
  'Chamber Music',
  'Orchestral',
  'Baroque',
  'Contemporary Classical',
  'Choral',
];

export const moods: string[] = [
  // --- melancholy / healing ---
  'makes you want to break shit and riot but in an empowering way',
  'feels like driving alone at 2am with nowhere to be',
  'the musical equivalent of a warm hug from someone you missed',
  'hits different when you realize you actually turned out okay',
  'makes you feel like the main character in a film nobody else has seen',
  'sounds like crying in the shower but in a healing way',
  'perfect for staring out a rain-soaked window and feeling deeply',
  'makes you want to slow dance alone in your kitchen at sunset',
  'the sonic version of letting go of something you held onto too long',
  'feels like nostalgia for a memory you never actually had',
  'the kind of song that makes a stranger feel like an old friend',
  'hits like the first warm day after a long brutal winter',
  'makes you feel invincible but in a quiet, private way',
  'sounds like falling in love with a city at golden hour',
  'the feeling of finishing something you thought you never would',
  'melancholy but make it beautiful — you feel sad in a good way',
  'makes your whole body want to move even if you swore you weren\'t dancing tonight',
  'the audio equivalent of watching the sun rise after pulling an all-nighter',
  'feels like the deep breath before something changes everything',
  'sounds like the version of yourself you\'re still becoming',
  'the sonic equivalent of texting back "lol" when you\'re actually not okay',
  'makes you want to reorganize your entire life at 11pm on a tuesday',
  'sounds like something beautiful rotting slowly and you can\'t look away',
  'the feeling of being completely alone in a crowd and somehow preferring it',
  'hits like an apology you never got but somehow still healed from',
  'makes you want to pick up a hobby you abandoned years ago for no reason',
  'sounds like two people who love each other but keep missing each other by five minutes',
  'the kind of song that makes you forgive yourself for something you\'ve been holding',
  'feels like being nineteen again but with the wisdom to actually enjoy it',
  'makes everything feel cinematic even if you\'re just doing dishes',
  'the feeling of packing a bag and not telling anyone where you\'re going',
  'sounds like a conversation you\'ve been rehearsing for months that you\'ll never actually have',
  'hits like finally admitting to yourself what you already knew',
  'makes you want to lie on the floor and stare at the ceiling until something makes sense',
  'feels like watching your old self from a distance and wishing you could warn them',
  'the kind of song you play loud enough that the neighbors can hear your feelings for you',
  'sounds like the last night in a place you\'ll never live again',
  'makes you want to call someone you haven\'t talked to in years at a completely unreasonable hour',
  'feels like being understood by someone who doesn\'t even speak your language',
  'the audio equivalent of a memory that hits you out of nowhere while you\'re in the grocery store',
  'sounds like falling apart gracefully — like you\'re okay with it this time',
  'makes you feel like the universe is conspiring in your favor for once',
  'the feeling right after a good cry when everything looks slightly cleaner',
  'sounds like someone wrote it just for you but they\'ve never met you',
  'makes you want to sit outside alone at night and just exist for a while',
  'feels like the exact moment summer turns into fall and you can\'t stop it',

  // --- sad / grief ---
  'sounds like missing someone who is still alive but not in your life anymore',
  'the kind of sad that feels almost sacred — too heavy to share with just anyone',
  'feels like grief with nowhere to go so it just sits in your chest',
  'sounds like writing a letter to someone you\'ll never actually send it to',
  'the audio equivalent of a place that used to matter but doesn\'t anymore',
  'makes the specific ache of something ending feel like it had a point',
  'feels like the last time you\'ll ever be the version of yourself you loved most',
  'sounds like finally crying about something you held together for way too long',
  'hits like realizing you\'ve already said your last goodbye to someone without knowing it',
  'the feeling of carrying something heavy with no one around to help you put it down',
  'sounds like loving someone in the past tense',
  'makes you grieve a future you had already planned out in your head',
  'feels like the silence after something important breaks and can\'t be fixed',
  'the kind of song that makes a whole year of pain feel like it finally has a shape',

  // --- happy / joyful ---
  'makes you feel like everything worked out exactly the way it was supposed to',
  'sounds like pure uncomplicated joy — no asterisks, no fine print',
  'feels like a surprise that actually surprises you for once',
  'makes you want to high-five strangers for no particular reason',
  'sounds like winning small and it being more than enough',
  'the audio equivalent of finding money in an old jacket pocket',
  'makes your whole face do something you can\'t control',
  'feels like a day where nothing went wrong and you noticed',
  'sounds like every good thing happening at the same time',
  'the kind of song that makes you smile before the first verse even finishes',
  'hits like the exact moment a weight you forgot you were carrying just lifts',
  'feels like laughing so hard you can\'t catch your breath and not wanting to',
  'sounds like being genuinely, stupidly happy and not caring who sees it',
  'makes you want to cook something good and eat it with people you love',

  // --- excited / hype ---
  'makes you want to sprint somewhere even if there\'s nowhere to be',
  'feels like the moment before the beat drops and everyone in the room already knows',
  'sounds like being first in line for something you\'ve waited your whole life for',
  'makes you pace around the room because sitting still is simply not an option',
  'the kind of song that turns a commute into a full music video',
  'hits like the night before the thing you\'ve been looking forward to for months',
  'sounds like everything happening all at once and somehow you\'re keeping up',
  'feels like the crowd going quiet right before something iconic',
  'makes your shoulders go up and your jaw drop a little at the same time',
  'sounds like a countdown hitting zero',
  'the feeling of finally being ready after a long time not being ready',
  'makes you want to call someone just to tell them this song exists',
  'hits like momentum — once it starts, nothing is stopping you',

  // --- angry / rebellious ---
  'sounds like being done explaining yourself to people who never listened anyway',
  'feels like burning something down just to watch something new grow from it',
  'the kind of angry that\'s actually grief in a different outfit',
  'makes you want to quit something you\'ve been too scared to quit for too long',
  'sounds like every time you stayed quiet when you should have said something',
  'hits like finally saying the thing you\'ve been swallowing for years',
  'feels like the energy of someone who stopped caring what the room thinks',
  'the sonic equivalent of walking out of something and not looking back',

  // --- peaceful / chill ---
  'sounds like having nowhere to be and actually being okay with it',
  'feels like the particular quiet of early morning when no one else is awake yet',
  'makes everything slow down to the speed it was always supposed to move at',
  'the audio equivalent of a long exhale you didn\'t know you were holding',
  'feels like permission to stop trying so hard for just a little while',
  'sounds like a sunday with no obligations and no guilt about it',
  'makes the world feel smaller in a good way — like it fits in your chest comfortably',
  'the feeling of sitting somewhere beautiful and not reaching for your phone',
  'hits like the calm after a storm when the air smells completely different',
  'sounds like doing one thing slowly and doing it well',

  // --- romantic ---
  'sounds like falling for someone and knowing it before you\'re ready to admit it',
  'feels like the beginning of something that\'s going to change you',
  'makes you want to reach across the table and hold someone\'s hand for no reason',
  'the kind of song that plays in your head when you think about a specific person',
  'sounds like loving someone from a distance and somehow that being enough',
  'feels like being chosen by someone who had every reason not to choose you',
  'the audio equivalent of butterflies that never quite went away',
  'sounds like every small moment that wasn\'t supposed to matter but ended up mattering most',

  // --- nostalgic ---
  'feels like a place you grew up in that doesn\'t exist the same way anymore',
  'sounds like being young and not knowing yet how temporary everything was',
  'makes you ache for a version of your life that was never quite real but still felt like home',
  'the audio equivalent of finding an old photo you completely forgot existed',
  'hits like the smell of something that takes you back somewhere specific and overwhelming',
  'sounds like the last summer before everything got complicated',
  'feels like growing up in slow motion and only realizing it now',
  'makes you miss a person you used to be before life edited them out of you',
];

export function getRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}
