export const genres: string[] = [
  // --- hip hop / rap ---
  'Lo-Fi Hip Hop',
  'Trap',
  'Trap Soul',
  'Boom Bap',
  'Cloud Rap',
  'Drill',
  'UK Drill',
  'Crunk',
  'Phonk',
  'Emo Rap',
  'Jazz Rap',
  'Gangsta Rap',
  'Conscious Hip Hop',
  'Chopped & Screwed',
  'Footwork',
  'Grime',
  'G-Funk',

  // --- r&b / soul ---
  'R&B',
  'Neo Soul',
  'Trap Soul',
  'Contemporary R&B',
  'Quiet Storm',
  'Gospel Blues',
  'Psychedelic Soul',
  'Motown',
  'Funk',
  'New Jack Swing',

  // --- pop ---
  'Hyperpop',
  'Synthpop',
  'Baroque Pop',
  'Chamber Pop',
  'Dream Pop',
  'Bubblegum Pop',
  'Art Pop',
  'City Pop',
  'Electropop',
  'Indie Pop',
  'K-Pop',
  'J-Pop',
  'Bedroom Pop',

  // --- rock / alternative ---
  'Shoegaze',
  'Post-Punk',
  'Math Rock',
  'Noise Rock',
  'Midwest Emo',
  'Post-Rock',
  'Grunge',
  'Indie Rock',
  'Psychedelic Rock',
  'Garage Rock',
  'Art Rock',
  'Glam Rock',
  'Stoner Rock',
  'Desert Rock',
  'Slowcore',
  'Emo',
  'Screamo',
  'Pop Punk',
  'Britpop',
  'Surf Rock',
  'Folk Rock',

  // --- metal ---
  'Doom Metal',
  'Black Metal',
  'Death Metal',
  'Sludge Metal',
  'Shoegaze Metal',
  'Post-Metal',
  'Nu-Metal',
  'Metalcore',
  'Progressive Metal',
  'Gothic Metal',

  // --- electronic ---
  'Ambient Electronic',
  'Synthwave',
  'Darkwave',
  'Ethereal Wave',
  'Vaporwave',
  'UK Garage',
  'House',
  'Deep House',
  'Tech House',
  'Acid House',
  'Chicago House',
  'Techno',
  'Detroit Techno',
  'Minimal Techno',
  'Trance',
  'Psytrance',
  'Drum and Bass',
  'Jungle',
  'Dubstep',
  'Future Bass',
  'IDM',
  'Glitch',
  'Chillwave',
  'Witch House',
  'Jersey Club',
  'Ambient',
  'New Age',
  'Trip Hop',

  // --- jazz ---
  'Jazz Fusion',
  'Nu Jazz',
  'Bebop',
  'Cool Jazz',
  'Hard Bop',
  'Free Jazz',
  'Smooth Jazz',
  'Acid Jazz',
  'Avant-Garde Jazz',
  'Modal Jazz',

  // --- folk / country / americana ---
  'Indie Folk',
  'Outlaw Country',
  'Americana',
  'Bluegrass',
  'Folk',
  'Anti-Folk',
  'Country Blues',
  'Alt-Country',
  'Appalachian Folk',
  'Singer-Songwriter',

  // --- latin / global ---
  'Afrobeats',
  'Bossa Nova',
  'Cumbia',
  'Reggaeton',
  'Latin Trap',
  'Salsa',
  'Samba',
  'Merengue',
  'Afro-Cuban Jazz',
  'Dembow',
  'Baile Funk',
  'Amapiano',
  'Afrohouse',
  'Dancehall',
  'Reggae',
  'Dub',
  'Soca',
  'Highlife',
  'Fela Kuti-era Afrobeat',
  'Flamenco',
  'Fado',

  // --- classical / orchestral ---
  'Neoclassical',
  'Minimalist Classical',
  'Chamber Music',
  'Orchestral',
  'Baroque',
  'Contemporary Classical',
  'Choral',
];

export const songVibes: string[] = [
  // --- melancholy / healing (15) ---
  'feels like driving alone at 2am with nowhere to be',
  'makes you feel like the main character in a film nobody else has seen',
  'sounds like crying in the shower but in a healing way',
  'perfect for staring out a rain-soaked window and feeling deeply',
  'the sonic version of letting go of something you held onto too long',
  'melancholy but make it beautiful — you feel sad in a good way',
  'sounds like something beautiful rotting slowly and you can\'t look away',
  'the feeling of being completely alone in a crowd and somehow preferring it',
  'hits like an apology you never got but somehow still healed from',
  'the kind of song that makes you forgive yourself for something you\'ve been holding',
  'the kind of song you play loud enough that the neighbors can hear your feelings for you',
  'sounds like falling apart gracefully — like you\'re okay with it this time',
  'the feeling right after a good cry when everything looks slightly cleaner',
  'sounds like someone wrote it just for you but they\'ve never met you',
  'sounds like the version of yourself you\'re still becoming',

  // --- sad / grief (15) ---
  'sounds like missing someone who is still alive but not in your life anymore',
  'the kind of sad that feels almost sacred — too heavy to share with just anyone',
  'feels like grief with nowhere to go so it just sits in your chest',
  'sounds like writing a letter to someone you\'ll never actually send it to',
  'the audio equivalent of a place that used to matter but doesn\'t anymore',
  'makes the specific ache of something ending feel like it had a point',
  'feels like the last time you\'ll ever be the version of yourself you loved most',
  'sounds like finally crying about something you held together for way too long',
  'hits like realizing you\'ve already said your last goodbye to someone without knowing it',
  'the feeling of carrying something heavy with no one around to help you put it down',
  'sounds like loving someone in the past tense',
  'makes you grieve a future you had already planned out in your head',
  'feels like the silence after something important breaks and can\'t be fixed',
  'the kind of song that makes a whole year of pain feel like it finally has a shape',
  'sounds like the moment you realize some doors only open from the inside and you lost the key',

  // --- happy / joyful (20) ---
  'makes you feel like everything worked out exactly the way it was supposed to',
  'sounds like pure uncomplicated joy — no asterisks, no fine print',
  'feels like a surprise that actually surprises you for once',
  'makes you want to high-five strangers for no particular reason',
  'sounds like winning small and it being more than enough',
  'the audio equivalent of finding money in an old jacket pocket',
  'makes your whole face do something you can\'t control',
  'feels like a day where nothing went wrong and you noticed',
  'sounds like every good thing happening at the same time',
  'the kind of song that makes you smile before the first verse even finishes',
  'hits like the exact moment a weight you forgot you were carrying just lifts',
  'feels like laughing so hard you can\'t catch your breath and not wanting to',
  'sounds like being genuinely, stupidly happy and not caring who sees it',
  'makes you want to cook something good and eat it with people you love',
  'the kind of happy that makes you text someone just to say you\'re thinking of them',
  'sounds like the first song at a party where everyone already knows the words',
  'makes you feel like the world is actually on your side today',
  'hits like getting the exact news you\'ve been waiting for and not knowing what to do with your hands',
  'sounds like summer when summer still meant something',
  'makes the ordinary feel like a gift you almost forgot to unwrap',

  // --- excited / hype (20) ---
  'makes you want to sprint somewhere even if there\'s nowhere to be',
  'feels like the moment before the beat drops and everyone in the room already knows',
  'sounds like being first in line for something you\'ve waited your whole life for',
  'makes you pace around the room because sitting still is simply not an option',
  'the kind of song that turns a commute into a full music video',
  'hits like the night before the thing you\'ve been looking forward to for months',
  'sounds like everything happening all at once and somehow you\'re keeping up',
  'feels like the crowd going quiet right before something iconic',
  'makes your shoulders go up and your jaw drop a little at the same time',
  'sounds like a countdown hitting zero',
  'the feeling of finally being ready after a long time not being ready',
  'makes you want to call someone just to tell them this song exists',
  'hits like momentum — once it starts, nothing is stopping you',
  'sounds like the opening credits of the best night of your life',
  'makes you feel like you could run through a wall and somehow that\'s a reasonable idea',
  'the kind of song that makes a whole room tilt toward the speakers at the same time',
  'hits like every door you\'ve ever knocked on finally opening at once',
  'feels like the engine turning over after a long cold stretch — everything catching at once',
  'sounds like going faster than you probably should and not even considering slowing down',
  'makes you want to do something big before the song ends',

  // --- angry / rebellious (15) ---
  'sounds like being done explaining yourself to people who never listened anyway',
  'feels like burning something down just to watch something new grow from it',
  'the kind of angry that\'s actually grief in a different outfit',
  'makes you want to quit something you\'ve been too scared to quit for too long',
  'sounds like every time you stayed quiet when you should have said something',
  'hits like finally saying the thing you\'ve been swallowing for years',
  'feels like the energy of someone who stopped caring what the room thinks',
  'the sonic equivalent of walking out of something and not looking back',
  'makes you want to break shit and riot but in an empowering way',
  'sounds like someone who has been patient for a very long time and just ran out',
  'hits like the moment you stopped asking for permission',
  'the kind of song that makes you feel dangerous in the best possible way',
  'sounds like rewriting every rule that was written without you in the room',
  'feels like the first no you\'ve said that you actually meant',
  'sounds like finally having nothing left to lose and realizing that\'s actually freedom',

  // --- peaceful / chill (20) ---
  'sounds like having nowhere to be and actually being okay with it',
  'feels like the particular quiet of early morning when no one else is awake yet',
  'makes everything slow down to the speed it was always supposed to move at',
  'the audio equivalent of a long exhale you didn\'t know you were holding',
  'feels like permission to stop trying so hard for just a little while',
  'sounds like a sunday with no obligations and no guilt about it',
  'makes the world feel smaller in a good way — like it fits in your chest comfortably',
  'the feeling of sitting somewhere beautiful and not reaching for your phone',
  'hits like the calm after a storm when the air smells completely different',
  'sounds like doing one thing slowly and doing it well',
  'feels like being understood by someone who doesn\'t even speak your language',
  'makes you want to sit outside alone at night and just exist for a while',
  'makes everything feel cinematic even if you\'re just doing dishes',
  'the sonic equivalent of a room with good light and nowhere you have to be',
  'sounds like late afternoon sun through a window when you have nothing to do but sit in it',
  'feels like the world turned the volume down and forgot to turn it back up',
  'makes you want to make tea and not rush it',
  'the kind of song that fills a room without taking up any space',
  'sounds like the easy silence between people who don\'t need to fill it',
  'hits like finally letting yourself rest without calling it laziness',

  // --- romantic (20) ---
  'sounds like falling for someone and knowing it before you\'re ready to admit it',
  'feels like the beginning of something that\'s going to change you',
  'makes you want to reach across the table and hold someone\'s hand for no reason',
  'the kind of song that plays in your head when you think about a specific person',
  'sounds like loving someone from a distance and somehow that being enough',
  'feels like being chosen by someone who had every reason not to choose you',
  'the audio equivalent of butterflies that never quite went away',
  'sounds like every small moment that wasn\'t supposed to matter but ended up mattering most',
  'sounds like falling in love with a city at golden hour',
  'makes you want to slow dance alone in your kitchen at sunset',
  'the kind of song you play when you want someone to stay a little longer',
  'sounds like the version of a person you only see when nobody else is around',
  'hits like making eye contact across a room and both of you knowing',
  'feels like being someone\'s favorite without them ever having to say it',
  'sounds like a first date where you both forgot to check the time',
  'the sonic equivalent of someone remembering the small thing you mentioned once',
  'makes you feel like being in love is actually the whole point',
  'sounds like every text you overthought and sent anyway',
  'feels like staying up too late talking about nothing and not wanting it to stop',
  'hits like the moment you realize you\'re already home',

  // --- nostalgic (20) ---
  'feels like a place you grew up in that doesn\'t exist the same way anymore',
  'sounds like being young and not knowing yet how temporary everything was',
  'makes you ache for a version of your life that was never quite real but still felt like home',
  'the audio equivalent of finding an old photo you completely forgot existed',
  'hits like the smell of something that takes you back somewhere specific and overwhelming',
  'sounds like the last summer before everything got complicated',
  'feels like growing up in slow motion and only realizing it now',
  'makes you miss a person you used to be before life edited them out of you',
  'feels like being nineteen again but with the wisdom to actually enjoy it',
  'makes you want to call someone you haven\'t talked to in years at a completely unreasonable hour',
  'the audio equivalent of a memory that hits you out of nowhere while you\'re in the grocery store',
  'feels like watching your old self from a distance and wishing you could warn them',
  'sounds like the last night in a place you\'ll never live again',
  'the kind of song that takes you to a specific moment you didn\'t know you remembered this clearly',
  'sounds like a friendship that ended without a fight and somehow that\'s worse',
  'makes you want to find the playlist you made at 16 and understand yourself better',
  'hits like visiting somewhere you used to love and realizing it\'s different now — or maybe you are',
  'sounds like the exact feeling of summer nights as a kid when the rules didn\'t apply',
  'the sonic equivalent of rewatching something you loved as a kid and feeling it completely differently',
  'makes you want to look up someone you lost track of and then decide not to',

  // --- confident / empowered (20) ---
  'sounds like the version of yourself you\'ve been working toward finally showing up',
  'hits like looking in the mirror and actually liking what you see',
  'makes you walk differently — like you know exactly where you\'re going',
  'the kind of song that makes you feel like the main character and the whole cast at once',
  'sounds like someone who has earned every single thing they have',
  'feels like finally taking up the space you were always supposed to occupy',
  'hits like remembering who you were before you started apologizing for it',
  'the sonic equivalent of a handshake that lands perfectly',
  'makes you feel like you could negotiate anything and win',
  'sounds like walking into a room and already knowing your worth before anyone speaks',
  'feels like the moment you realized you outgrew something that used to intimidate you',
  'hits like showing up as the person you always hoped you\'d become',
  'sounds like making a decision and not second-guessing it for once',
  'makes you want to do the thing you\'ve been putting off because suddenly it just seems doable',
  'the kind of song that turns doubt into fuel',
  'sounds like the first time someone said yes to something you worked a long time for',
  'feels like your own highlight reel playing in your head and you actually deserve it',
  'hits like realizing you\'re the one people look to now',
  'sounds like having done the work and knowing it',
  'makes you feel like the hardest part is already behind you and what\'s ahead is yours',

  // --- anxious / introspective (15) ---
  'the sonic equivalent of texting back "lol" when you\'re actually not okay',
  'makes you want to reorganize your entire life at 11pm on a tuesday',
  'sounds like a conversation you\'ve been rehearsing for months that you\'ll never actually have',
  'makes you want to lie on the floor and stare at the ceiling until something makes sense',
  'the feeling of packing a bag and not telling anyone where you\'re going',
  'hits like finally admitting to yourself what you already knew',
  'sounds like the 3am version of a question you can\'t stop asking',
  'feels like scrolling back through old messages looking for where it changed',
  'the kind of song that makes you pause mid-task and sit with something you\'ve been avoiding',
  'sounds like the part of your brain that won\'t let you sleep running at full volume',
  'hits like the moment you realize you\'ve been holding your breath for a really long time',
  'feels like being stuck between two versions of yourself and not knowing which one wins',
  'sounds like every unanswered question you\'ve trained yourself not to ask out loud',
  'makes you want to take a very long walk with no destination and work something out',
  'the feeling of knowing exactly what\'s wrong and having absolutely no idea what to do about it',

  // --- bittersweet (15) ---
  'feels like the exact moment summer turns into fall and you can\'t stop it',
  'sounds like two people who love each other but keep missing each other by five minutes',
  'the audio equivalent of watching the sun rise after pulling an all-nighter',
  'feels like the deep breath before something changes everything',
  'hits different when you realize you actually turned out okay',
  'the musical equivalent of a warm hug from someone you missed',
  'hits like the first warm day after a long brutal winter',
  'sounds like being happy about something and sad about it at the exact same time',
  'the kind of song that makes an ending feel like it was worth it',
  'hits like getting everything you wanted and realizing the wanting was part of it',
  'sounds like a goodbye that was also somehow the best part',
  'feels like the last page of a book you weren\'t ready to finish',
  'makes you smile and ache at the same time and somehow that feels exactly right',
  'hits like a chapter closing that you wouldn\'t rewrite even if you could',
  'sounds like the feeling of being grateful for something that hurt',
];

export const gamingVibes: string[] = [
  // --- tilted / frustrated ---
  'playing like the game owes you something and it doesn\'t',
  'one bad death away from uninstalling',
  'blaming lag even though you know that\'s not it',
  'typing something in chat and then deleting it',
  'making the same mistake but faster',
  'convinced everyone else is the problem',
  'muted the team but still somehow mad at them',
  'lost the mental before the first round even started',
  'playing angry, which is just playing bad but louder',
  'every death feels like a personal attack',
  'queuing again immediately, which is the wrong move',
  'knows exactly what they\'re doing wrong and doing it anyway',
  'the one more game before bed that turned into four',

  // --- locked in / zone ---
  'seeing the play before it happens',
  'not talking, not blinking, just winning',
  'operating at a frequency the rest of the lobby can\'t hear',
  'muscle memory doing things the brain hasn\'t approved yet',
  'the team goes quiet because they know it\'s handled',
  'every decision landing exactly right and acting like it\'s normal',
  'tunnel vision but make it productive',
  'playing like they\'ve already seen the VOD',

  // --- carrying ---
  'doing the work of three people and somehow still getting blamed',
  'solo queuing but winning like they\'re with pros',
  'the team is the challenge and the opponents are the warmup',
  'keeping everyone alive through sheer refusal to let it go',
  'single-handedly making a 3v5 feel competitive',
  'the damage numbers look like a typo',

  // --- getting carried ---
  'contributing morally',
  'alive by proximity to greatness',
  'teammate is a god and they are a grateful witness',
  'doing just enough to not get blamed',
  'trusting the process, which means trusting them',
  'the assist was intentional',

  // --- demoralized / checked out ---
  'still queuing but not really here anymore',
  'playing the next game like they already know how it ends',
  'the vibe is gone and everyone can feel it',
  'running it down but legally',
  'mechanically present, mentally already in bed',
  'third loss in a row and the eyes are glazed over',
  'knows it\'s a loss but won\'t say it out loud',

  // --- winning / on a roll ---
  'the lobby can feel it and they\'re scared',
  'win streak energy — everything is going right and it almost feels wrong',
  'calling shots that keep working for no explainable reason',
  'playing with a confidence that hasn\'t been earned but also hasn\'t been wrong yet',
  'they can\'t figure out what\'s happening and honestly neither can we',
  'this is the session that gets brought up for weeks',

  // --- end of session ---
  'knows it\'s time to log off but queuing one more',
  'the skill is gone but the hope is still there',
  'this is either the perfect game to end on or a trap',
  'the session was a journey and this is the finale',
  'closing the client and already thinking about tomorrow\'s session',
  'signed off on a win — smart, rare, and the right call',
  'ended on a loss which means tomorrow is already scheduled',
  'the best session in recent memory and already scared it won\'t happen again',
  'three hours disappeared and there are zero complaints',
  'said nothing wrong in voice chat tonight — a personal record',
  'the recap is already forming in the group chat',
  'the hands need a minute but the brain isn\'t ready to stop',
  'leaving on good terms with the game tonight — that doesn\'t always happen',
  'the kind of session that reminds you why you do this',
  'screen off, headset down, already thinking about the next one',

  // --- tilted / frustrated (extended) ---
  'respawning with the energy of someone who has given up but won\'t say it',
  'the chat is muted and the headset is one bad round away from coming off',
  'playing since the beginning of time and somehow getting worse',
  'the kind of tilted where wrong item builds start feeling justified',
  'said "last game" forty-five minutes ago',
  'the opponent is not better, just luckier — and that\'s the story they\'re going with',
  'flaming themselves in their own head worse than anyone in chat ever could',
  'the ping is fine and that\'s somehow the most frustrating part',
  'one good round away from being okay, one bad round away from logging off forever',
  'has opinions about every teammate\'s decisions and zero awareness of their own',
  'queuing with the intent to win and the energy of someone who already lost',
  'the game hasn\'t started and they\'re already tilted from the last one',
  'fixing crosshair placement after every single death instead of once',
  'the lobby is bad. the server is bad. everything is bad.',
  'forgot this is a game and made it a personality instead',
  'rotating wrong, buying wrong, dying wrong — with full confidence throughout',
  'alt-tabbing between deaths to look at literally anything else',
  'every loss feels rigged and every win feels like a fluke this session',
  'respawned with a plan and immediately forgot the plan',
  'the uninstall button has never looked so reasonable',

  // --- locked in / zone (extended) ---
  'the warm-up finally clicked and the whole session belongs to them now',
  'communicating in two words or less and it\'s working every time',
  'every fight is a conclusion before it starts',
  'playing at a pace nobody else in the lobby can match right now',
  'no wasted movement, no wasted words, just results',
  'clicked in before the loading screen even finished',
  'reading the game like they wrote the patch notes',
  'the confidence is grounded, the mechanics are clean, it\'s just not fair right now',
  'the headset went on and a completely different person came out',
  'not making plays — making decisions that happen to look like plays',
  'the crosshair finds the head before the brain finishes processing the target',
  'outplaying people so smoothly they don\'t realize it happened until the kill feed',
  'running on the specific calm that only comes from doing this ten thousand times',
  'the playlist is right, the chair is right, the vibe is right — everything follows',
  'this is the version of them the group talks about when explaining why they keep playing together',

  // --- carrying (extended) ---
  'the scoreboard looks like a mistake but it\'s not',
  'winning in spite of everything and everyone around them',
  'every rotation covers for someone who didn\'t rotate',
  'first one in and somehow still the last one standing',
  'carried so hard the team thinks they won together',
  'the only person who looked at the minimap this entire game',
  'buying utility they\'re going to use for four people who won\'t throw their own',
  'the team is a liability and they are the asset',
  'playing at a level that makes the scoreline look closer than it actually feels',
  'if they go down the game is over and everyone knows it including them',
  'a one-person army somehow still with a positive attitude about the situation',
  'the eliminations are clean, the rotations are clean, the teammates are not',
  'doing more with less and making it look easier than it should be',
  'hitting enough shots for everyone because the team can\'t find theirs tonight',
  'the win condition, and the only person who has figured that out',

  // --- getting carried (extended) ---
  'statistically present',
  'running around confidently in the wrong direction',
  'their deaths are buying time and that\'s a form of contribution they\'re claiming',
  'not helping but not hurting either — and in this economy that counts',
  'the unofficial moral support player of the session',
  'cheering louder than anyone even with two kills on the board',
  'the assists are carrying the KDA enough to maintain basic dignity',
  'playing with the enthusiasm of someone who genuinely thinks they\'re helping',
  'watching greatness happen from two steps behind it',
  'in the lobby, technically, which counts for something',
  'the emotional support role — unofficial, unpaid, apparently necessary',
  'the frag count doesn\'t reflect the impact. it just doesn\'t. trust.',
  'running in so the carry knows exactly where the enemies are',
  'the warmup dummy the team needed and somehow got',
  'not a liability. well. not a major one. the jury is still out.',

  // --- demoralized / checked out (extended) ---
  'the session ended mentally two games ago',
  'pressing buttons with the energy of someone filling out mandatory paperwork',
  'trying just hard enough to not get called out for not trying',
  'the loss streak has entered the stage where nothing means anything anymore',
  'every queue pop is a fresh opportunity to be disappointed in new ways',
  'looking at the clock every three minutes hoping enough time has passed to stop',
  'the game sense is gone, the mechanics are gone, the snacks are the only anchor',
  'has mentally uninstalled while still physically playing — it\'s complicated',
  'the team can feel the dead energy radiating through the mic',
  'agreed to one more game six games ago',
  'not griefing. just done. there\'s a difference. barely.',
  'the goal has shifted from winning to having a story about how bad the lobby was',
  'running it like a simulation — no stakes, no feelings, no frags',
  'if this were a job they would have quiet-quit forty minutes ago',
  'the spirit has logged off. the body remains. barely.',

  // --- winning / on a roll (extended) ---
  'every bad play from the enemy team is an opportunity being taken immediately',
  'the gap between this lobby and them is widening and everyone can see it',
  'confidence that compounds — every good play making the next one easier',
  'so far ahead they could afford to be generous and they\'re choosing not to be',
  'the score is flattering but also completely accurate',
  'the better team from minute one and the lobby knew it by minute three',
  'running it back immediately because the momentum is real and it can be felt',
  'playing relaxed because playing relaxed is what winning looks like right now',
  'every early fight going their way for no reason and nobody\'s questioning it',
  'the other team is adapting. it\'s not working.',
  'the lead is comfortable enough to have fun and they\'re having fun',
  'on a streak long enough to say "we don\'t lose" without irony',
  'every game feels manageable right now — not jinxing it by asking why',
  'this is the energy that carries into the next day and makes practice feel unnecessary',
  'the session that gets screenshotted and posted in the group chat',

  // --- squad / duo energy ---
  'the synergy is built-in — no callouts needed, just results',
  'playing with someone who makes the whole game make more sense',
  'two people sharing one brain cell and somehow that\'s enough',
  'the chemistry is on tonight and the opponents are already aware',
  'every play sets up the next one and both people know it before it happens',
  'the kind of squad where losing together still feels better than winning alone',
  'covering each other\'s mistakes before the other one notices they happened',
  'been playing together long enough to argue mid-round and still clutch',
  'callouts are half-sentences and they still land every time',
  'two completely different playstyles adding up to the same right answer',
  'the squad queue means something tonight and everyone can feel it',
  'outnumbered in every fight and somehow still taking them',
  'the group chat is active, the gameplay is active — a rare and beautiful combination',
  'individually mid but collectively nasty — that\'s the duo experience in full',
  'playing for each other more than for the win and somehow that\'s why they\'re winning',

  // --- trash talk / big energy ---
  'talking the most in voice chat and somehow backing every word of it up',
  'said something bold before the game and now the scoreboard agrees',
  'the confidence is loud but the gameplay is louder',
  'claimed they were going to hard carry and then did exactly that',
  'living in the opponents\' heads rent-free and fully aware of it',
  'predicting plays out loud and then making them, which should probably be illegal',
  'the ego is enormous and unfortunately completely earned right now',
  'playing with the audacity of someone who hasn\'t lost recently enough to be humble',
  'the energy in voice chat is unhinged and also winning, somehow',
  'the callout came before the peek and it was right — they\'re not going to let that go',

  // --- clutch moments ---
  'one person, one chance, and they took it without hesitating',
  'the kind of play that makes voice chat go completely silent for one second',
  'should not have won that fight and did anyway',
  'calculated. probably. the math checks out.',
  'the clutch wasn\'t clean but it counted — that\'s the only thing that matters',
  'made something out of a situation that had no business working at all',
  'the whole team was watching and the whole team gets to talk about it now',
  'defused with less time than should have been physically possible',
  'the play of the game was accidental and they\'re claiming it fully anyway',
  'the 1v3 that nobody expected including them — especially them',

  // --- grinding / ranked ---
  'playing ranked like it\'s a second job and not being compensated enough',
  'one LP away from something and four losses away from it simultaneously',
  'the elo is wrong and the queue is how they\'re going to prove it',
  'hardstuck for two weeks and just queued again anyway',
  'the rank doesn\'t reflect the skill. or maybe it does. that\'s the scary part.',
  'grinding with the discipline of someone who has accepted this will take a while',
  'the MMR is a ceiling they hit with their head every single session',
  'three promos deep and feeling every single one of them physically',
  'the mental fortitude required to climb is separate from the mechanics and both are running low',
  'queuing ranked at midnight because that\'s when the good players are online. or so the theory goes.',
];

export function getRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

let moodDeck: string[] = [];

function refillDeck(): void {
  moodDeck = [...songVibes].sort(() => Math.random() - 0.5);
}

export function getUniqueVibe(): { vibe: string; cycleComplete: boolean } {
  const cycleComplete = moodDeck.length === 0;
  if (cycleComplete) refillDeck();
  return { vibe: moodDeck.pop()!, cycleComplete };
}

let gamingDeck: string[] = [];

function refillGamingDeck(): void {
  gamingDeck = [...gamingVibes].sort(() => Math.random() - 0.5);
}

export function getUniqueGamingVibe(): { vibe: string; cycleComplete: boolean } {
  const cycleComplete = gamingDeck.length === 0;
  if (cycleComplete) refillGamingDeck();
  return { vibe: gamingDeck.pop()!, cycleComplete };
}

export const nightEndedVibes: string[] = [
  // --- warm wrap-up ---
  'the kind of night that makes the group chat feel like a trophy',
  'didn\'t win every game but won the night somehow',
  'everyone stayed until the end and that means something',
  'the night had a vibe from the first queue and never lost it',
  'a session that didn\'t need to be anything more than what it was',
  'everyone showed up and that\'s the whole story',
  'the kind of night the group was built for',
  'the night ended at the right time which almost never happens',
  'the wins mattered but the company mattered more',
  'signed off satisfied, which is rarer than it sounds',
  'another night in the books — one of the better ones',
  'the only thing wrong with tonight is that it ended',
  'the night deserved to end here and it did',
  'the final GG hit different tonight',
  'closed the client feeling like a person, which isn\'t guaranteed after a gaming session',

  // --- squad appreciation ---
  'the group played like a group tonight',
  'one of those sessions where being online felt like being in the same room',
  'the kind of chaos that only works because of who you\'re in it with',
  'felt like a team tonight — not just a group of people queued together',
  'the kind of night where the trash talk was love and everyone knew it',
  'the kind of night that makes you grateful you have this group',
  'the chaos was shared and the shared chaos is what made it good',
  'closing out with the same group that started it — underrated ending',
  'a night that proved the group still has it',
  'the friends logged off but the energy is going to stick around for a minute',
  'everyone played worse than they could have and it didn\'t matter at all',
  'the kind of session where being bad at the game didn\'t matter',
  'the kind of night you\'ll reference in six months with zero context and everyone will know',

  // --- the clip, the moment ---
  'the clip is already being edited in someone\'s head right now',
  'everyone\'s going to think about that one moment for at least three days',
  'the kills were quotable, the misses were more quotable, the night was perfect',
  'the night that gets brought up the next time someone asks "remember when"',
  'the highlights are locked in, the squad delivered',
  'the session had a story arc and it actually resolved',
  'the group chat is going to be busy tonight and deservedly so',

  // --- tired but satisfied ---
  'voices are tired, hands are tired, already can\'t wait to do it again',
  'the headset comes off and the room is quiet and it was worth every second',
  'three hours of gameplay and a week\'s worth of memories',
  'everyone left the session better than they entered it, at least mood-wise',
  'packed it in before it went bad — rare discipline, deserves recognition',
  'logged off with more than they started with — not lp, just good',
  'the lobby is empty now but it was full where it counted',
  'the scoreboard is closed but the energy lingers',
  'everyone stayed a little longer than they planned and that\'s the real review',
  'nobody wanted to call it but someone had to and now it\'s done and it was good',

  // --- reflective / nostalgic ---
  'the kind of night that earns its own nickname in the group chat',
  'tomorrow\'s session already has a lot to live up to',
  'the memories from tonight cost nothing and will last longer than the rank',
  'the post-game voice chat went longer than the actual games and that\'s fine',
  'a night that started slow and found its rhythm — the best kind',
  'the vibe carried from the first lobby to the last and that\'s genuinely rare',
  'the rage was real, the recovery was realer, the night was the realest',
  'three hours disappeared and there are zero complaints',
  'the session didn\'t go as planned and went better than planned simultaneously',
  'the night had weight to it in a good way',
  'the kind of session you wouldn\'t trade even if the rank doesn\'t show it',

  // --- the send-off ---
  'the banter was at its peak and somehow the gameplay followed',
  'a session built entirely on vibes and somehow it all worked',
  'the playlist hit, the lobby hit, the vibe hit — everything aligned tonight',
  'the last game ended perfectly — or imperfectly — and either way it was right',
  'screen off, headset down, the night is officially in the books',
];

let nightEndedDeck: string[] = [];

function refillNightEndedDeck(): void {
  nightEndedDeck = [...nightEndedVibes].sort(() => Math.random() - 0.5);
}

export function getUniqueNightEndedVibe(): { vibe: string; cycleComplete: boolean } {
  const cycleComplete = nightEndedDeck.length === 0;
  if (cycleComplete) refillNightEndedDeck();
  return { vibe: nightEndedDeck.pop()!, cycleComplete };
}

export const vibeMatchMetrics: string[] = [
  'synergy',
  'vibe sync',
  'chemistry',
  'aligned',
  'matched',
  'in sync',
  'locked in',
  'on the same wavelength',
  'tuned in',
  'wired the same',
  'hardwired',
  'synchronized',
  'entangled',
  'riding the same wave',
  'calibrated',
  'coded the same',
  'dialed in',
  'sympatico',
  'resonating',
  'on the same team',
  'running the same build',
  'sharing a brain cell',
  'operating on the same frequency',
];

export const vibeMatchDescriptions: string[] = [
  // --- chaotic duo energy ---
  'one brings the chaos, one enables it, and together they are everyone else\'s problem',
  'individually fine, together a problem in the best possible way',
  'would 100% go in on a bad idea together if it sounded fun enough',
  'if one of them is doing something stupid the other one is already there',
  'one of them suggested the bad idea, the other one said let\'s go, and here we are',
  'the two people in the group most likely to have the exact same unhinged idea at the same time',
  'peak enablers of each other\'s worst decisions and most memorable nights',
  'the two most likely to make a terrible call and somehow pull it off',
  'would absolutely sabotage a win condition if it meant getting a funnier clip',
  'the friendship that runs on chaos, snacks, and the refusal to go to sleep',

  // --- gaming duo dynamics ---
  'the duo that goes 0-10 and blames each other but still queues again tomorrow',
  'unstoppable together until one tilts and takes the other one with them',
  'both think they\'re the carry and neither is completely wrong',
  'one carries, one watches, and the one watching has the most to say afterward',
  'the synergy is real but the communication is chaotic and somehow it still works',
  'best when they\'re both locked in and genuinely terrifying when they\'re not',
  'the duo the lobby either loves or fears and there\'s no in between',
  'either completely synchronized or completely off — no in between ever',
  'the duo that communicates better through gameplay than through actual words',
  'been through enough bad games together that the bad games don\'t even count anymore',

  // --- friend group classics ---
  'would throw each other under the bus and immediately feel bad about it',
  'the kind of friends who roast each other constantly and would fight anyone else who tried',
  'have had the same argument seventeen times and will have it again',
  'will agree on everything except the one thing that matters most right now',
  'the type to hype each other up for things that maybe shouldn\'t be hyped up',
  'the friends who know exactly which buttons to press and press them anyway',
  'would 1v1 each other for bragging rights about literally anything',
  'one of them is always right and the other one thinks they are',
  'the type to blame each other first and defend each other second — but always defend second',
  'communicate entirely in references nobody else in the lobby understands',

  // --- ride or die ---
  'the kind of duo where losing together stings less than winning alone',
  'been playing together long enough that the silence means something',
  'could run it back with zero discussion and somehow be on the same page',
  'the friendship that needs zero context and zero explanation — it just is what it is',
  'the two most likely to look at each other mid-session and already know',
  'peak co-dependent gamers — one doesn\'t queue without checking if the other is on',
  'the friendship built on shared Ls and the full refusal to learn from them',
  'one of them is the reason they\'re in this situation and the other is why they got out',
  'same energy, different volume — and somehow that works every time',
  'the duo where one is always two seconds from flaming and the other talks them down',

  // --- chaotic neutral friendship ---
  'the two people most likely to stay on voice chat until 4am for no reason at all',
  'one of them has been carrying the vibe all session and the other owes them',
  'different vibes, same frequency — it shouldn\'t work but it absolutely does',
  'the friendship that only makes sense from the inside',
  'the chaos agents of the group — separately manageable, together unpredictable',
  'one of them is the reason the group stays together, the other is the reason it\'s interesting',
  'the two people most likely to agree to something before hearing the full plan',
  'would argue about the wrong thing for an hour and then forget what started it',
  'the squad that makes every session worth a story even if the games weren\'t',
  'the kind of duo where the banter is the whole point and the game is just background noise',

  // --- extended ---
  'the two people most likely to make a bad decision at the same time and both defend it',
  'one of them is always five minutes late to queue and the other one always forgives it',
  'the kind of friendship where the insults are affectionate and everyone else can tell',
  'been in enough lobbies together that they know each other\'s bad habits better than their own',
  'the duo that everyone in the group knows not to put on opposite teams',
  'will absolutely take the fall for each other and argue about who deserved it more',
  'two people who have never once agreed on a strategy and somehow keep winning anyway',
  'the kind of friends who can go weeks without talking and pick up exactly where they left off',
  'one of them always has the aux and the other one always has opinions about it',
  'been carrying each other in different ways for so long neither one keeps score anymore',
  'the two most likely to stay on voice chat just talking after everyone else logs off',
  'they have a dynamic that is genuinely hard to explain to someone who wasn\'t there',
  'the kind of duo that makes losing feel like a shared bit rather than an actual loss',
  'one of them is the plan, the other one is the reason the plan changes halfway through',
  'would 100% lie to the group for each other and be bad at it and do it anyway',
  'the friendship that gets louder and more chaotic the later it gets',
  'two people who have seen each other at their worst in a game and showed up again anyway',
  'the type to hype each other into something terrible and then be surprised together',
  'the kind of pair where one bad game from one of them affects the other\'s whole session',
  'been friends long enough that they can tell what mood the other one is in from two words in vc',
  'the duo that other people in the lobby can sense — something about the way they play together',
  'one of them always goes too far, the other one always lets it happen, and it always works out',
  'the friendship that runs entirely on bad ideas, worse timing, and somehow good outcomes',
  'two people who would never admit how much they enjoy playing together and everyone already knows',
  'the kind of chemistry that makes a 2v5 feel like a reasonable proposition',
];

export const excuses: string[] = [
  'the enemy team was clearly smurfing',
  'my mouse clicked on its own',
  'the lag spike was real — you can\'t prove otherwise',
  'i was warming up that whole game',
  'someone walked in front of my screen at the worst possible moment',
  'that champion/agent is broken and needs a nerf immediately',
  'i haven\'t eaten today and it absolutely affected my reaction time',
  'the server was off — everyone felt it, nobody said it',
  'my teammates were not communicating',
  'i was playing on the wrong sensitivity the entire time',
  'my chair is uncomfortable and it throws off my aim',
  'the sun was hitting my monitor at a very specific and unforgivable angle',
  'the enemy just got lucky — statistically that cannot keep happening',
  'i was trying a new playstyle and it takes time to develop',
  'my hands were cold',
  'i need a new mouse — this one is double-clicking',
  'the ping was showing 20 but it felt like 200 the whole game',
  'i was in my head the entire time because of that first death',
  'someone in that lobby was clearly cheating',
  'the matchmaking put us against a pre-made five stack',
  'i was testing something — it didn\'t work but now i have data',
  'the audio cues were completely off this game',
  'i didn\'t sleep enough last night and it affects literally everything',
  'my keyboard is sticking on a key',
  'honestly i was just having too much fun to care about winning',
  'that map is specifically designed against my playstyle',
  'the team comp was unwinnable from champion/agent select',
  'i was carrying mentally — it just didn\'t show on the scoreboard',
  'my desk was wobbling and it affected my aim more than people realize',
  'i had to sneeze at the worst possible moment',
  'the enemy had a counter to literally everything we were doing',
  'i was one item/ability away from popping off — they killed me right before',
  'the patch changed something i haven\'t fully adjusted to yet',
  'honestly my monitor\'s refresh rate is holding me back at this point',
  'i got targeted the whole game — they were clearly scared of me',
  'the hitboxes were wrong — everyone knows it, nobody says it',
  'i wasn\'t trying that game specifically',
  'the RNG was not on our side and that is a statistical fact',
  'my room is too warm and it genuinely affects focus',
  'the enemy had way more hours on that character than is reasonable for a normal person',
  'i could hear someone talking in the background and completely lost focus',
  'i was one second away from winning that fight — one second',
  'the game is just in a bad state right now — it\'s not us',
  'i was playing for fun and they were playing for their actual lives',
  'the early game snowballed and there was mathematically nothing to do',
  'i would have won that 1v1 on any other day — any other day',
  'i need to recalibrate — this loss was actually information',
  'we played fine — the algorithm decided this one wasn\'t ours',
  'my headset broke mid-round and i missed every callout',
  'i was distracted by something in my peripheral vision the whole time',
];

export const copes: string[] = [
  'that was actually good practice',
  'we were clearly the moral victors',
  'they needed that win more than us',
  'the real victory was the friends we made along the way',
  'we were running an experiment and now we have the data',
  'losing builds character — we have a lot of character now',
  'that was a practice game — the real ones start next session',
  'we let them win — you wouldn\'t understand the long game',
  'that wasn\'t our final form',
  'we were clearly sandbagging',
  'on any other day, completely different story',
  'that loss was for the algorithm — we\'re going to pop off next game',
  'we learned more from that L than they learned from winning',
  'the scoreboard doesn\'t capture the full picture of what we were doing out there',
  'we were playing 4D chess and the game only rendered the 3D part',
  'they got lucky — every single time — the whole game',
  'a loss this clean means we\'re statistically overdue for a win',
  'we were placed in the wrong lobby — the skill gap was insulting to us',
  'we played exactly how we wanted to — the result was irrelevant',
  'this is a growth moment — i can physically feel myself growing',
  'our early game was actually perfect — late game is a separate conversation',
  'we\'re just built for longer games — this one ended too fast',
  'this is the dip before the glow up — trust the process',
  'statistically we are due — it\'s just math at this point',
  'we were the better team and history will remember that',
  'everyone has a bad game — ours just happened to be that one',
  'this motivates us — they fueled something tonight',
  'the enemy will never be as happy as they are right now — that\'s actually sad for them',
  'we played our game — they played theirs — ours was cooler',
  'that was a social experiment and we got exactly the data we needed',
  'sometimes the universe just has other plans — not our fault',
  'we\'re in our villain arc — the win streak starts next game',
  'peak performance was there — it was hiding — it comes out next game',
  'honestly they should be grateful we weren\'t trying',
  'we were playing around our weaknesses to identify them — mission accomplished',
  'the comeback we almost had was incredible though',
  'we were one play away — one — play — away',
  'the matchmaking did this, not us',
  'this is how legends are made — they always struggle first',
  'we\'re not losing — we\'re in a character arc',
  'good — we needed humbling — we are appropriately humbled — back to work',
  'the real win was not completely flaming each other and we achieved that',
  'their win expires in 24 hours — ours is forever when it happens',
  'we were simply testing the limits — now we know',
  'if this were a movie we\'d be in the training montage part right now',
  'we just gave them false confidence — this is a setup',
  'the numbers were wrong but the vibes were immaculate',
  'we\'re not hardstuck — we\'re hardstuck on purpose',
  'this one doesn\'t count — everyone knows which ones count',
  'we almost had it and almost is closer than most people get',
];

export const mostLikelyActions: string[] = [
  'to int round 1 and blame the team',
  'to dodge the second the lobby looks rough',
  'to go 0/8 and ask if anyone wants to run it back',
  'to instalock and say nothing',
  'to mute everyone and then have opinions about the loss',
  'to flame and then apologize three rounds later',
  'to hard carry and bring it up for the rest of the night',
  'to die first and spectate everyone\'s gameplay with full commentary',
  'to say "one more game" and mean six more games',
  'to go afk mid-round and come back like nothing happened',
  'to blame ping when the ping is fine',
  'to pick the worst agent/champ for the situation and pop off anyway',
  'to type a paragraph in chat and then delete it',
  'to rotate wrong and cost us the round',
  'to hard int and claim they were testing something',
  'to stay up way too late and be terrible at the game because of it',
  'to get one good game and think they\'re completely back',
  'to rage quit with two rounds left',
  'to call the play wrong and be very loud about it',
  'to single-handedly tilt the entire lobby',
  'to buy a support item and play like a duelist anyway',
  'to get one kill and immediately start talking like they\'re the best player alive',
  'to die to the same thing three times without adjusting once',
  'to ping the objective seventeen times and then not take it',
  'to be the reason we lost and also the loudest person in voice chat about it',
  'to go even and call it a carry',
  'to drop the best performance of the night in the one game we lose',
  'to flame the jungler from top lane without looking at the minimap once',
  'to have a meltdown and then queue again immediately',
  'to call a play that works for completely the wrong reasons',
  'to not buy wards and ask why nobody has vision',
  'to be completely checked out and then pop off in the final round',
  'to die to something avoidable and immediately explain why it wasn\'t',
  'to be the last one alive and somehow make it work',
  'to alt-tab at the most important moment of the game',
  'to make the wrong call at full confidence and somehow be half right',
  'to respawn with a completely different attitude and fix the whole vibe',
  'to take a fight they shouldn\'t win and win it anyway',
  'to not say a word for three rounds and then suddenly have a lot to say',
  'to type gg early and then be the reason we didn\'t lose early',
  'to get tilted first and take someone else down with them',
  'to play something off-meta and have it be uncomfortably effective',
  'to carry the vibes even when they can\'t carry the scoreboard',
  'to have a perfect game and immediately have opinions about how everyone else played',
  'to refuse to group up and somehow make it work anyway',
  'to lose their lane and blame the jungler before anyone checks the scoreboard',
  'to stay in a losing fight two seconds longer than they should and come out alive',
  'to get a double kill and act like they never left',
  'to not read the map once and be genuinely surprised by the result',
];

export const mostLikelyResponses: string[] = [
  '{name}. Easily. No contest.',
  'The group has decided: {name} {action}.',
  'Without hesitation — {name} {action}.',
  'The bot ran the numbers. {name} is most likely {action}.',
  'After extensive deliberation: {name} {action}. Every time.',
  '{name} — most likely {action}. This is not a roast. This is data.',
  'First ballot. No debate. {name} {action}.',
  'Statistically, historically, and spiritually — {name} {action}.',
  'The committee didn\'t even need to meet. {name} {action}.',
  '{name} is most likely {action}. The bot has spoken. We move on.',
  'Not even close. {name} {action}.',
  'Signed, sealed, delivered — {name} {action}.',
  'The verdict required zero deliberation: {name} {action}.',
  'If anyone was going {action}, it was always going to be {name}.',
  '{name} {action}. Please hold your applause.',
  'The algorithm, the vibes, and common sense all agree: {name} {action}.',
  'No debate. No discussion. {name} {action}.',
  '{name} {action} and will not be apologizing for it.',
  'Results are in. {name} {action}. Final answer.',
  '{name} was nominated, seconded, and confirmed: {action}.',
  'The nomination goes to {name} — most likely {action}.',
  'Ask anyone. They\'ll say {name}. Most likely {action}.',
  'This was never a question. It was always {name}. {action}.',
  'Unanimous. {name} {action}.',
  'The record shows {name} is most likely {action}. The record doesn\'t lie.',
  '{name} {action}. Nobody is surprised. Nobody.',
  'The answer was {name}. The question was most likely {action}.',
  'Zero hesitation from the bot. {name} {action}.',
  'The group pointed to {name} before the question was finished. {action}.',
  '{name} {action}. This has been confirmed by multiple sources.',
  'It\'s {name}. It was always going to be {name}. {action}.',
  'The bot consulted the data. The data said {name}. {action}.',
  '{name} — confirmed. {action}. No notes.',
  'Uncontested. {name} {action}.',
  'The group didn\'t even blink. {name} {action}.',
  '{name} {action}. The science is in.',
  'We ran a poll internally. {name} {action}. Every single vote.',
  'Shocking to no one: {name} {action}.',
  'The answer has always been {name}. {action}.',
  '{name} {action}. This is the way.',
  'By a landslide — {name} {action}.',
  'The bot didn\'t even have to think. {name} {action}.',
  '{name} {action}. The prophecy has been fulfilled.',
  'We all knew. We just needed confirmation. {name} {action}.',
  'The evidence is overwhelming. {name} {action}.',
  '{name} {action}. Let the record reflect.',
  'Certified. {name} {action}.',
  'The crowd points unanimously to {name}. {action}.',
  '{name} {action}. Signed by this bot. Notarized.',
  'The selection process was brief. {name} {action}.',
  '{name} was the only possible answer. {action}.',
  'The forecast calls for {name} {action}.',
  'One name came up. It was {name}. {action}.',
  '{name} {action}. We accept this outcome.',
  'There was never any doubt. {name} {action}.',
  '{name} {action}. History will remember this moment.',
  'The group consensus arrived in under a second: {name} {action}.',
  'Without even looking — {name} {action}.',
  '{name} {action}. And they know it too.',
  'The prediction is sealed: {name} {action}.',
];

export const blameResponses: string[] = [
  'The blame has been officially assigned to {name}. This is binding.',
  'The council has deliberated. It was {name}. Unanimously.',
  '{name}. It was {name}. It was always {name}.',
  'After a thorough investigation, {name} has been found guilty. Court is adjourned.',
  'The numbers don\'t lie. The evidence points to {name}.',
  '{name} has accepted the blame. They didn\'t have a choice.',
  'The people have voted. {name} takes the L on this one.',
  'Filed, stamped, and certified: {name} is responsible.',
  '{name}. No further questions.',
  'An independent review has concluded that {name} is to blame. We are so sorry.',
  'The blame committee met for approximately three seconds and landed on {name}.',
  '{name} has been selected as today\'s sacrifice. Nothing personal.',
  'After a careful review of the footage, {name} did that.',
  'The verdict is in. The verdict is {name}.',
  '{name} has been charged with first-degree losing. Bail has been denied.',
  'By the power vested in this bot, {name} is hereby blamed. Good day.',
  'The investigation is closed. It was {name}. It was always going to be {name}.',
  '{name} has been identified as the primary culprit. Secondary culprits: everyone else, a little.',
  'Sources close to the situation confirm: {name} did this.',
  'The court finds {name} guilty on all counts. The sentence is carrying next game.',
  'The data has been reviewed. {name} is the data.',
  '{name} was identified at the scene. The scene was the loss.',
  '{name} has been formally notified. They have 0 business days to respond.',
  'The jury was out for four seconds. {name}. Guilty.',
  'This is not a debate. This is a declaration. {name} did this.',
  'The blame has been triangulated and it leads directly to {name}.',
  '{name} has been selected by the algorithm. The algorithm is never wrong.',
  'A detailed report has been filed. The report says {name}.',
  '{name} is hereby responsible for the outcome of this game and possibly several others.',
  'The committee has reached a consensus: {name}. No abstentions.',
  '{name} has been flagged, reviewed, and confirmed as the source.',
  'It gives me no pleasure to announce that {name} did this. Some pleasure. Not a lot.',
  'The math checked out. The math says {name}.',
  '{name} — this is your official notice. You know what you did.',
  'The blame is not up for debate. It lives at {name} now.',
  '{name} has been found at fault by a panel of their peers, all of whom agree.',
  'The investigation team consisted of one bot. The bot says {name}.',
  '{name} — formally, legally, and spiritually — takes the blame for this one.',
  'Blame issued. Recipient: {name}. Delivery: confirmed.',
];

export const clutchResponses: string[] = [
  '{name} clutches. It\'s not even close.',
  '{name} is built for this moment. Clutch confirmed.',
  'Cool under pressure. Cooler than they should be. {name} clutches.',
  'The lobby went quiet. {name} delivered.',
  '{name} said not today and meant every word of it.',
  'This is what they train for. {name} clutches.',
  '{name} doesn\'t feel pressure — they apply it.',
  'Clutch. {name} was never going to miss that.',
  '{name} saw the play before it happened and made it happen anyway.',
  'Everyone watching. Nobody doubting. {name} clutches.',
  '{name} was made for this. The game knew it before they did.',
  'Nobody blinked. {name} clutched.',
  'The pressure? {name} doesn\'t know her.',
  '{name} saw chaos and said "mine." Clutch.',
  'The play was clean. The result was clean. {name} was clean. Clutch.',
  'First try. {name} clutches and acts like it happens every time.',
  '{name} goes ice cold when it matters. Clutch.',
  'The odds were not in their favor. {name} didn\'t care. Clutch.',
  '{name} lowkey been waiting for this moment the whole game. Clutch.',
  'Zero hesitation. Zero doubt. {name} clutches.',
  'The team needed one person to step up. {name} stepped all the way up.',
  '{name} said relax and then performed immaculately. Clutch.',
  'That was not supposed to work. {name} made it work. Clutch.',
  '{name} turned nothing into something. The clutch is official.',
  'Calm. Calculated. Completely unhinged to watch. {name} clutches.',
  'The moment asked for a lot. {name} had exactly enough. Clutch.',
  '{name} woke up and chose violence — the profitable kind. Clutch.',
  'Everyone in the lobby felt it. {name} delivered.',
  '{name} was calm because {name} already knew. Clutch confirmed.',
  'The clutch has been certified. {name} is the reason.',
];

export const chokeResponses: string[] = [
  '{name} chokes. It\'s not even close.',
  '{name} had it. And then didn\'t have it.',
  'The pressure got to {name}. It happens. Not often. But here we are.',
  '{name} chokes. We don\'t talk about this one.',
  'The moment was too big. {name} will be fine. Eventually.',
  '{name} — respectfully — crumbled.',
  'It was right there. {name} saw it. Still. Choke.',
  '{name} chokes. The lore has been updated accordingly.',
  'A historic choke from {name}. We move on.',
  '{name} chokes. No notes. No excuses. It is what it is.',
  '{name} has choked. We process this together.',
  'The vibes were there. The execution was not. {name} chokes.',
  '{name} — we love you. But you choked. These are both true.',
  'The situation called for {name} to deliver. {name} did not deliver.',
  'A moment of silence for {name}, who had every opportunity.',
  '{name} chokes. This is now part of the lore whether they like it or not.',
  'The highlight reel will not include this one. {name} chokes.',
  '{name} saw the opening and decided against it. Choke.',
  'In another timeline {name} clutched. This is not that timeline.',
  '{name} — this one stays in the vault. Choke.',
  'The hands betrayed the mind. {name} chokes.',
  '{name} chokes. The group will never forget. The group will say they forgot.',
  'So close. So very close. {name} chokes and we move forward.',
  '{name} chokes. This is the most we will say about it.',
  'The moment was winnable. {name} found a way to lose it. Choke confirmed.',
  '{name} has been issued a choke. There is no appeals process.',
  'The play was there. The follow-through was not. {name} chokes.',
  '{name} — deep breath — you choked. It happens to the best. Today it happened to you.',
  'We don\'t blame {name}. We simply note that {name} choked. Noted.',
  'The final assessment: {name} choked. The session continues.',
];
